#!/bin/bash
#modo netcat pc server
killall cryptcat > /dev/null 2> /dev/null
date
echo Esperando conexion entrante sea paciente
echo Tips: pegar texto con la ruedita del mouse.
cryptcat -vvlp 6898 -k "$ENTRY3" &
exec  Eterm -T Cryptcat_Servidor_Yo --scrollbar-type=xterm --buttonbar=off -g 60x20+0+300 -e cryptcat -vvlp 6896 -k "$ENTRY3"
exit 0


